sequenceDiagram
    Actor User
    Participant System

    User ->> System : Inputs name
    User ->> System : Selects New Hampshire location
    System -->> User : Provides air quality and pollen report